package com.example.wellnessquest.model;

import java.io.Serializable;
import java.util.List;

public class Quest implements Serializable {
    private String id; // Id for every quest
    private String title; // Title of the quest
    private String description; // Text that describes the objective of the quest
    private String category; // "Fitness" or "Mind"
    private boolean isCompleted; // Check if quest is completed or not
    private int coins; // Coins generated by completing quest
    private List<String> validTags; // Tags that are used to match against ml-kit generated tags for the image sent in by user

    public Quest(String id, String title, String description, String category, boolean isCompleted, int coins, List<String> validTags) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.category = category;
        this.isCompleted = isCompleted;
        this.coins = coins;
        this.validTags = validTags;
    }

    // Getters
    public String getId() {
        return id;
    }

    public List<String> getValidTags() {
        return validTags;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public String getCategory() {
        return category;
    }

    public boolean isCompleted() {
        return isCompleted;
    }

    public int getCoins() {
        return coins;
    }

    // Setters
    public void setId(String id) {
        this.id = id;
    }

    public void setValidTags(List<String> validTags) {
        this.validTags = validTags;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    public void setDescription(String description) {
        this.description = description;
    }

    public String setCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setCompleted(boolean completed) {
        isCompleted = completed;
    }

    public void setCoins(int coins) {
        this.coins = coins;
    }

    public boolean isComplete() {
        return isCompleted;
    }

    public int getRewardCoins() {
        return coins;
    }

    public void markComplete() {
        this.isCompleted = true;
    }
}